@startuml Bookstore
skinparam backgroundColor #f9f9f9
skinparam state {
    BackgroundColor White
    BorderColor Black
    FontColor Black
}

state App {
    [*] --> HomePage : Start

    HomePage --> LoginSite : "Login"
    HomePage --> Suchen : "Suchen"
    HomePage --> Details : "Details anzeigen"

    state LoginSite {
        [*] --> AnmeldeFormular : "Login-Eingabe"
        state entscheidung <<choice>>
        AnmeldeFormular --> entscheidung : "einloggen"
        entscheidung --> AnmeldeFormular : "Login fehlgeschlagen"
        entscheidung --> Angemeldet : "Login erfolgreich"
    }

    Angemeldet --> BuchAnlegen : "Hinzufügen"
    BuchAnlegen --> HomePage : "erfolgreich angelegt"
    Angemeldet --> Suchen : "Suchen"

    state Suchen {
        [*] --> Suchformular : "Suchkriterien eingeben"
        state bedingung <<choice>>
        Suchformular --> Ergebnisse : "Suchen"
        Ergebnisse --> bedingung : "Bearbeiten auswählen"
        Ergebnisse --> bedingung : "Löschen auswählen"
        Ergebnisse --> Details : "Details auswählen"

        bedingung --> Bearbeiten : "Angemeldet"
        bedingung --> Löschen : "Angemeldet"
        bedingung --> Ergebnisse : "Nicht Angemeldet"
    }

    Details --> HomePage : "Zurück zur Übersicht"
    Details --> Bearbeiten : "Bearbeiten starten [wenn angemeldet]"
    Details --> Löschen : "Löschen bestätigen [wenn angemeldet]"
}

@enduml
